### ISSUE TITLE
ERROR! the role 'manager' was not found

### ISSUE THREAD

**Issue by maliblatt** [osism/cfg-generics#249]
I had to change the line to the following to get the manager update working:

  roles:
    - role: osism.manager

https://github.com/osism/cfg-generics/blob/4cc73a476d4566bc153a58af4a4fa6ed304997c8/environments/manager/playbook-manager.yml#L11

Is that intended?

**Comment by berendt** [comment]
@maliblatt Can you check if osism-update-manager works for the update?

**Comment by maliblatt** [comment]
(osism-upgrade) dragon@manager01-dev:/opt/configuration$ osism-update-manager
- changing role osism.manager from master to master
- extracting osism.manager to /opt/configuration/environments/manager/roles/osism.manager
- osism.manager (master) was installed successfully
Vault password: 
ERROR! the role 'manager' was not found in osism.services:ansible.legacy:/opt/configuration/environments/manager/roles:/home/dragon/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/opt/configuration/environments/manager

The error appears to be in '/opt/configuration/environments/manager/playbook-manager.yml': line 11, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - role: manager
      ^ here


After changing the role to osism.manager the osism-update-manager works without problems

**Comment by maliblatt** [comment]
After some further testing it came out, the problem was related to our very old manager installation. After going with run.sh ... I can use the osism-update-manager without problems now.
Thanks @berendt for the hints!
