### ISSUE TITLE
50-infrastruture: Sort the entries

### ISSUE THREAD

**Issue by ra-rau** [osism/cfg-generics#268]
Maybe we should sort the entries in an alphabetic order.

**Comment by berendt** [comment]
Maybe we should sort all files?

As a second step we add a check that ensures that the files remain sorted in the future. I know at least one person very well who does not pay attention ;)

**Comment by ra-rau** [comment]
For the check i make this new issue:
https://github.com/osism/cfg-generics/issues/272
